### ISSUE TITLE
Shorten long titles

### ISSUE THREAD

**Issue by Korni22** [bahlo/beats-status#4]
It would be very nice if there was a parameter in the .env file to shorten titles like those:
`ⓑ I Know There's Gonna Be (Good Times) [feat. Young Thug &amp; Popcaan] - Jamie xx` 
to
`I Know There's Gonna Be - Jamie xx`
would be shorter for those of us, who use this with TextBar in their menubar :)

**Comment by bahlo** [comment]
Nice idea, would you check the overall length of the text or always remove the features?

**Comment by bahlo** [comment]
We now just remove all features if the option is set. :+1:
